### PR TITLE
Adding expanded information on lessons endpoint

### PR DESCRIPTION
**Pull request by kyprifog**

### CODE REVIEW

**Comment by armilam** [comment]
@kyprifog, I'm assuming this is ready for review? Please provide a description on all PRs to give some context.

If this needs to wait for another PR to be merged, say so. If this is ready to be reviewed, assign it. Without context, it's really hard to determine your intent with this. I can't tell if you want this to be reviewed or if you're waiting for something.

**Comment by kyprifog** [comment]
Sorry, ready for review, meant to assign to you.

**Comment by armilam** [comment]
Once you get this added information on the courses endpoint per https://github.com/lessonly/lesson.ly/pull/1944#issuecomment-195061520, update the doc here as well.

**Comment by kyprifog** [comment]
made a new PR that included this going to close this one.

**Pull request closed without merging**
